ons_metrics:
  CPI:
    topic: "economy/inflationandpriceindices"
    cdid: "l55o"
    dataset: "mm23"
    name: "Consumer Price Index"
    unit: "%"
    frequency: "Monthly"
  CORE_CPI:
    topic: "economy/inflationandpriceindices"
    cdid: "dkc6"
    dataset: "mm23"
    name: "Core Consumer Price Index"
    unit: "%"
    frequency: "Monthly"
  GDP_QOQ:
    topic: "economy/grossdomesticproductgdp"
    cdid: "ihyq"
    dataset: "pn2"
    name: "GDP Quarter-on-Quarter Growth"
    unit: "%"
    frequency: "Quarterly"
  GDP_YOY:
    topic: "economy/grossdomesticproductgdp"
    cdid: "ihyp"
    dataset: "pn2"
    name: "GDP Year-on-Year Growth"
    unit: "%"
    frequency: "Yearly"
  UNRATE:
    topic: "employmentandlabourmarket/peoplenotinwork/unemployment"
    cdid: "mgsx"
    dataset: "lms"
    name: "Unemployment Rate (16+)"
    unit: "%"
    frequency: "Monthly"
  EMPRATE:
    topic: "employmentandlabourmarket/peopleinwork/employmentandemployeetypes"
    cdid: "lf24"
    dataset: "lms"
    name: "Employment Rate (16-64)"
    unit: "%"
    frequency: "Monthly"
  WAGE_GROWTH:
    topic: "employmentandlabourmarket/peopleinwork/earningsandworkinghours"
    cdid: "kai9"
    dataset: "lms"
    name: "Average Weekly Earnings Growth"
    unit: "%"
    frequency: "Monthly"
  HOUSE_PRICE_GROWTH:
    topic: "economy/inflationandpriceindices"
    cdid: "czbl"
    dataset: "mm23"
    name: "Housing Cost Inflation (YoY % Change)"
    unit: "%"
    frequency: "Monthly"

boe_metrics:
  BANK_RATE_DA:
    series_code: "IUDBEDR"
    name: "Official Bank Rate (Daily)"
    unit: "%"
    frequency: "Daily"
  BANK_RATE_MO:
    series_code: "IUMABEDR"
    name: "Official Bank Rate (Monthly average)"
    unit: "%"
    frequency: "Monthly"
  SONIA:
    series_code: "IUDSOIA"
    name: "(Sterling Overnight Index Average) Interest Rate"
    unit: "%"
    frequency: "Daily"
  # Exchange Rates & Competitiveness
  STERLING_ERI_MO:
    series_code: "XUMABK67"
    name: "Sterling Effective Exchange Rate Index (Monthly Average, Jan 2005 = 100)"
    unit: "Index"
    frequency: "Monthly"
  USD_GBP_SPOT_MO:
    series_code: "XUMAUSS"
    name: "USD per GBP Spot Exchange Rate (Monthly Average)"
    unit: "$"
    frequency: "Monthly"
  EUR_GBP_SPOT_MO:
    series_code: "XUMAERS"
    name: "EUR per GBP Spot Exchange Rate (Monthly Average)"
    unit: "EUR"
    frequency: "Monthly"

  # Housing Market & Consumer Credit
  MORTGAGE_2YR_75LTV_MO:
    series_code: "IUMBV34"
    name: "Monthly Average Interest Rate on 2-Year Fixed Rate Mortgages (75% LTV)"
    unit: "%"
    frequency: "Monthly"
  NET_LENDING_DWELLINGS_MO:
    series_code: "LPMVTVJ"
    name: "Net Secured Lending to Individuals"
    unit: "GBP Millions"
    frequency: "Monthly"
  NET_CONSUMER_CREDIT_MO:
    series_code: "LPMB4TU"
    name: "Net Consumer Credit Excluding Credit Card Lending"
    unit: "GBP Millions"
    frequency: "Monthly"

  # Monetary Aggregates (Liquidity)
  M4_GROWTH_MO:
    series_code: "RPMB56Q"
    name: "M4 Money Supply Growth (Excluding Intermediate OFCs)"
    unit: "%"
    frequency: "Monthly"
  NOTES_COINS_GROWTH_MO:
    series_code: "LPMVQUU"
    name: "Notes and Coin in Circulation Growth"
    unit: "%"
    frequency: "Monthly"

  # Corporate & Business Finance
  NET_LENDING_CORP_MO:
    series_code: "LPMVWNU"
    name: "Lending to UK Non-Financial Businesses Growth"
    unit: "%"
    frequency: "Monthly"
  CORP_OVERDRAFT_COST_MO:
    series_code: "CFMBJ82"
    name: "Average Cost of New Other Loans to Private Non-Financial Corporations"
    unit: "%"
    frequency: "Monthly"
